### ISSUE TITLE
container support

### ISSUE THREAD

**Issue by vincentserpoul** [noodlehaus/lemp-setup-runbook#1]
Hi sir, can not do docker! How?

**Comment by noodlehaus** [comment]
Create one and I'll adopt it! :D

**Comment by vincentserpoul** [comment]
i leave you the enjoyment of configuring your VM :)
if i had to build smtg today, id probably go for fastly edge or gke cloudrun

**Comment by noodlehaus** [comment]
i'm too lazy to try something new atm :D
